// <auto-generated />
using System;
using MagicVillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251217181435_seed_data_villas_fix_createddate_staticvalue")]
    partial class seed_data_villas_fix_createddate_staticvalue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaSqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amenity = "",
                            AreaSqft = 1000,
                            CreatedDate = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "A Royal Villa description highlights ultimate luxury, blending opulent decor (crystal chandeliers, silk carpets, marble floors) with exclusive amenities like private pools/Jacuzzis, sea views, multiple en-suite bedrooms, maid's quarters, fine dining areas, and high-tech features, all designed for prestige and relaxation, echoing palace grandeur in a private sanctuary.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Royal_villa_of_Durres_01.jpg/960px-Royal_villa_of_Durres_01.jpg?20191004113828",
                            Name = "Rolyal Villa",
                            Occupancy = 20,
                            Rate = 5000.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            Amenity = "",
                            AreaSqft = 600,
                            CreatedDate = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxury Pool Villa description highlights ultimate luxury, blending opulent decor (crystal chandeliers, silk carpets, marble floors) with exclusive amenities like private pools/Jacuzzis, sea views, multiple en-suite bedrooms, maid's quarters, fine dining areas, and high-tech features, all designed for prestige and relaxation, echoing palace grandeur in a private sanctuary.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pool_villa.jpg/960px-Pool_villa.jpg?20111226054028",
                            Name = "Luxury Pool Villa",
                            Occupancy = 10,
                            Rate = 800.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            Amenity = "",
                            AreaSqft = 450,
                            CreatedDate = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Pool Villa description highlights ultimate luxury, blending opulent decor (crystal chandeliers, silk carpets, marble floors) with exclusive amenities like private pools/Jacuzzis, sea views, multiple en-suite bedrooms, maid's quarters, fine dining areas, and high-tech features, all designed for prestige and relaxation, echoing palace grandeur in a private sanctuary.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Backyardpool.jpg/960px-Backyardpool.jpg",
                            Name = "Pool Villa",
                            Occupancy = 5,
                            Rate = 600.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            Amenity = "",
                            AreaSqft = 590,
                            CreatedDate = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Sea View Villa description highlights ultimate luxury, blending opulent decor (crystal chandeliers, silk carpets, marble floors) with exclusive amenities like private pools/Jacuzzis, sea views, multiple en-suite bedrooms, maid's quarters, fine dining areas, and high-tech features, all designed for prestige and relaxation, echoing palace grandeur in a private sanctuary.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Coronado_beach_house.jpg/960px-Coronado_beach_house.jpg",
                            Name = "Sea View Villa",
                            Occupancy = 6,
                            Rate = 750.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            Amenity = "",
                            AreaSqft = 400,
                            CreatedDate = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Leak View Villa description highlights ultimate luxury, blending opulent decor (crystal chandeliers, silk carpets, marble floors) with exclusive amenities like private pools/Jacuzzis, sea views, multiple en-suite bedrooms, maid's quarters, fine dining areas, and high-tech features, all designed for prestige and relaxation, echoing palace grandeur in a private sanctuary.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/9/9e/06VillaBalbianello.jpg",
                            Name = "Leak View Villa",
                            Occupancy = 10,
                            Rate = 450.0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
