BEGIN TRY
	BEGIN TRAN
	 INSERT INTO Names VALUES(5,'COCO',1);
	-- INSERT INTO Names VALUES(5,'SHOSO',1);
	-- next will raise error
	 INSERT INTO Names VALUES(6,'SHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSOSHOSO',1);
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK
END CATCH